spring:
  application:
    name: bangjjack
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/auth/login/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
  data:
    redis:
      host: localhost
      port: 6379

server-uri: http://localhost:8080
front-uri: http://localhost:5173

jwt:
  access:
    secret: ${JWT_ACCESS}
    expiration-seconds: 259200
